Update map layer on parameter select
openaq/openaq.org pull request #488
Opened 2020-12-17 18:42 UTC by AliceR

This updates the map when the user selects a parameter in the small (quite hidden) legend dropdown, and also reflects the change when a url is loaded with the parameter `parameter` set.

The synchronization of source and layers, parent and children is a bit adventurous, took me a while to get it to work and still feels not 100% - would love your feedback and opinions here!

2020-12-17 19:13 UTC, jvntf requested changes
Some small comments. I like the approach, cleaning up the old layers from the useEffect return is really nice!

2020-12-17 19:13 UTC, jvntf commented on app/assets/scripts/components/map/legend.js
>  import { generateLegendStops } from '../../utils/colors';
not exactly sure the issue, but seeing NaN produced on several parameters. This must be coming from an undefined parameterMax? can we get this from the API?

Also after clicking on a view params, I see too many updates on the legend. on initial load of this param, the legend looks correct
![image](https://user-images.githubusercontent.com/19439427/102532011-4f3fde80-4071-11eb-9887-06290af06a26.png)

2020-12-18 10:55 UTC, AliceR commented on app/assets/scripts/components/map/legend.js
> +export default function Legend({ parameters, activeParameter }) {
Took note of this issue here: https://github.com/openaq/openaq.org/projects/1#card-51488474

2020-12-18 11:09 UTC, AliceR commented
Thanks @jvntf , since the overall approach is working for you, I'll merge into #476 at this point and continue from there.

2020-12-18 11:14 UTC, merged