Compare locations
openaq/openaq.org pull request #523
Opened 2021-01-07 14:26 UTC by danielfdsilva

In this PR:
- Had some problems with sass when setting up the project, so had to update some modules. I think I managed to solve the problem but I'd like to know if works for everyone else.
- Add back the compare page using the new `/averages` endpoint to display data on the chart.
- Fix the header cards on the homepage using the new `?order_by=random` option and display average measurements like the compare page.
- Convert the `Home` component to functional with hooks.
- Add a "No listed city" default when there's no city available - on the compare page, hub cards and single location.

2021-01-07 23:11 UTC, rwegener2 requested changes
* home page loads much faster (and doesn't crash) 🎉 
* thanks for suggesting doing something about the lack of city name Daniel.  I think having "no listed city" on the cards is clearer and cleaner.
* Where it says _"Comparing < dropdown > values for local times"_ would it be easy enough to limit that list to only the pollutants available at one or more of the stations being used in the comparison?  There are a lot more variables now so listing them all means the majority of the time when you select a parameter it isn't available.
* On a similar note to the point above, could we add a list of the parameters available below the city name?  Something like "Reporting: PM2.5 mass, CO2, ..."
* All but one of the stations I tried worked. The one that gave me trouble was:
`http://localhost:3000/#/compare/Alicante%20Lane/US%20Diplomatic%20Post%3A%20Dhaka?parameter=28`.  I think it was that second on in Dhaka that was causing the issue.  Here's my developer tools error:
<img width="1287" alt="Screen Shot 2021-01-07 at 5 08 01 PM" src="https://user-images.githubusercontent.com/35503632/103954977-e943f580-510a-11eb-9d07-0eced2202f15.png">

In all thanks for bringing this component into the interface and upgrading to hooks! 🚀

2021-01-08 01:54 UTC, necoline reviewed
It's great to see so many updates to hooks 🎉 

It's a pretty large PR, so I mostly skimmed through it and checked for functionality.

The sass upgrades work for me.

2021-01-08 01:54 UTC, necoline commented on app/assets/scripts/actions/compare.js
> +      parameter: 'pm25',
These names are currently being updated. You can pass the parameter id here instead and that will remain constant

2021-01-08 10:34 UTC, danielfdsilva commented
@necoline @rwegener2 Feedback addressed:
- Values in Compare dropdown must be present in at least one locations
- Added "Reporting..." line to the compare location header
- Fix error handling
- Use parameter id instead of name
- Fix conflicts with "testing" branch

2021-01-08 10:45 UTC, AliceR commented
@danielfdsilva What do you think about splitting those huge files into smaller components? You can see how we did it with the other views. Right now they are so big Github even hides the diff! This makes reviewing as well as future maintenance more difficult than it should be.

2021-01-08 11:22 UTC, danielfdsilva commented
@AliceR agreed. done

2021-01-08 12:16 UTC, AliceR approved these changes
briefly tested the branch running locally and everything looks good. 

@rwegener2 not sure about the url you posted above, but I think you should use the location numeric id instead of the name in the url, like http://localhost:3000/#/compare/35822?parameter=130 - was this an old url you stored somewhere in your browser history, or did you access it by following a link in the ui?

2021-01-08 15:02 UTC, danielfdsilva commented
@AliceR That's the old url style. Now the locations are referenced by ids

2021-01-08 15:16 UTC, merged